<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="2">
  <testsuite name="Root Suite" timestamp="2021-03-10T10:23:09" tests="0" file="cypress/integration/register.feature" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="A user registers into the application" timestamp="2021-03-10T10:23:09" tests="1" time="0.0000" failures="2">
    <testcase name="A user registers into the application A new user registers in the application successfully" time="0.0000" classname="A new user registers in the application successfully">
      <failure message="Timed out after waiting `60000ms` for your remote page to load.

Your page did not fire its `load` event within `60000ms`.

You can try increasing the `pageLoadTimeout` value in `cypress.json` to wait longer.

Browsers will not fire the `load` event until all stylesheets and scripts are done downloading.

When this `load` event occurs, Cypress will continue running commands." type="CypressError"><![CDATA[CypressError: Timed out after waiting `60000ms` for your remote page to load.

Your page did not fire its `load` event within `60000ms`.

You can try increasing the `pageLoadTimeout` value in `cypress.json` to wait longer.

Browsers will not fire the `load` event until all stylesheets and scripts are done downloading.

When this `load` event occurs, Cypress will continue running commands.
    at timedOutWaitingForPageLoad (https://www.zinio.com/__cypress/runner/cypress_runner.js:158128:13)
    at https://www.zinio.com/__cypress/runner/cypress_runner.js:159112:16
    at tryCatcher (https://www.zinio.com/__cypress/runner/cypress_runner.js:10765:23)
    at https://www.zinio.com/__cypress/runner/cypress_runner.js:5887:41
    at tryCatcher (https://www.zinio.com/__cypress/runner/cypress_runner.js:10765:23)
    at Promise._settlePromiseFromHandler (https://www.zinio.com/__cypress/runner/cypress_runner.js:8700:31)
    at Promise._settlePromise (https://www.zinio.com/__cypress/runner/cypress_runner.js:8757:18)
    at Promise._settlePromise0 (https://www.zinio.com/__cypress/runner/cypress_runner.js:8802:10)
    at Promise._settlePromises (https://www.zinio.com/__cypress/runner/cypress_runner.js:8878:18)
    at _drainQueueStep (https://www.zinio.com/__cypress/runner/cypress_runner.js:5472:12)
    at _drainQueue (https://www.zinio.com/__cypress/runner/cypress_runner.js:5465:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.zinio.com/__cypress/runner/cypress_runner.js:5481:5)
    at Async.drainQueues (https://www.zinio.com/__cypress/runner/cypress_runner.js:5351:14)
From Your Spec Code:
    at Function.visit (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:150:10)
    at Context.eval (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:11:29)
    at Context.resolveAndRunStepDefinition (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:11926:9)
    at Context.eval (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:11267:35)
From Your Spec Code:
    at Function.visit (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:150:10)
    at Context.eval (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:11:29)
    at Context.resolveAndRunStepDefinition (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:11926:9)
    at Context.eval (https://www.zinio.com/__cypress/tests?p=cypress/integration/register.feature:11267:35)]]></failure>
    </testcase>
    <testcase name="A user registers into the application &quot;after all&quot; hook for &quot;A new user registers in the application successfully&quot;" time="0.0000" classname="&quot;after all&quot; hook for &quot;A new user registers in the application successfully&quot;">
      <failure message="Cypress command timeout of `4000ms` exceeded.

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `A user registers into the a...`" type="CypressError"><![CDATA[CypressError: Cypress command timeout of `4000ms` exceeded.

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `A user registers into the a...`
    at cypressErr (https://www.zinio.com/__cypress/runner/cypress_runner.js:174135:18)
    at Object.errByPath (https://www.zinio.com/__cypress/runner/cypress_runner.js:174186:10)
    at https://www.zinio.com/__cypress/runner/cypress_runner.js:175780:29]]></failure>
    </testcase>
  </testsuite>
</testsuites>